var member = [
{"phone": "No.1:",  "name": "小宠物<无瑕的紫晶珠蜒>等珠蜒4件套（彩虹屁效果哦），限定国服"},
{"phone": "No.2:",  "name": "平衡车"},
{"phone": "No.3:",  "name": "肴肉"},
{"phone": "No.4:",  "name": "桂林罗汉果+时光徽章+柑橘"},
{"phone": "No.5:",  "name": "手作冷吃兔+牛肉干（真空邮寄或当面）+千钧版本2CD免喷权"},
{"phone": "No.6:",  "name": "STEAM200游戏任选"},
{"phone": "No.7:",  "name": "480+装等任意职业一枚（纯手工）或台服季卡"},
{"phone": "No.8:",  "name": "steam游戏300以内"},
{"phone": "No.9:",  "name": "坚果年货大礼包两盒"},
{"phone": "No.10:", "name": "硬核三件套（戴森球+缺氧+取景器）"},
{"phone": "No.11:", "name": "国服两张月卡或台服两张月卡"},
{"phone": "No.12:", "name": "瑞格尔B1家庭投影仪"},
{"phone": "No.13:", "name": "去年gwp还在"},
{"phone": "No.14:", "name": "正宗重庆老火锅自炒火锅底料4斤"},
{"phone": "No.15:", "name": "京东/淘宝价值1000内桌搭配件任选"},
{"phone": "No.16:", "name": "碧蓝幻想relink/steam游戏合计200内"},
{"phone": "No.17:", "name": "steam200内游戏自选"},
{"phone": "No.18:", "name": "steam200内游戏自选"},
{"phone": "No.19:", "name": "dota2饰品宝瓶 or steam300内游戏自选 or 小吃特产大礼包（本人自选觉得好吃的）"},
]
