var member = [
{"phone": "No.1:", "name": "驭龙术-巨龙竞赛大满贯(黄金)"},
{"phone": "No.2:", "name": "夜空之歌服务器20wG"},
{"phone": "No.3:", "name": "台服月卡+加速器一个月，不可折现"},
{"phone": "No.4:", "name": "台服月卡等值金币-夜空之歌服务器+20低保打工"},
{"phone": "No.5:", "name": "玩家国度ROG游侠NX 104键+红包168"},
{"phone": "No.6:", "name": "现金红包99+半套强制性军训一次"},
{"phone": "No.7:", "name": "Steam国区200以内游戏任选"},
{"phone": "No.8:", "name": "台服50万金币"},
{"phone": "No.9:", "name": "gpw一代"},
{"phone": "No.10:", "name": "20低保  或者贝儿限定两件"},
{"phone": "No.11:", "name": "20万金币+真爱坐牢+3星鞋子附魔+stance限量款一双"},
{"phone": "No.12:", "name": "台服月卡/Steam国区100以内游戏任选+大郎该吃药了套餐"},
{"phone": "No.13:", "name": "月卡"},
{"phone": "No.14:", "name": "海鲜干货礼包+南瓜奖励车"},
{"phone": "No.15:", "name": "台服季卡没金币"},
{"phone": "No.16:", "name": "GTA6或台服季卡"},
{"phone": "No.17:", "name": "月卡折现红包"},
{"phone": "No.18:", "name": "2022宝瓶二一套（CK除外）"},
{"phone": "No.19:", "name": "大表哥2:Ultimate Edition / 地平线 5 标准版 / 台服月卡"},
{"phone": "No.20:", "name": "月卡折现红包，替我去艾泽拉斯驰骋吧"},
{"phone": "No.21:", "name": "福临门小样套盒"},
{"phone": "No.22:", "name": "5斤葡萄干或150r折现"},
{"phone": "No.23:", "name": "半年卡一张"},

]
